display_name: Leafz

icon: assets/app-icon-with-dash-ltr.png

summary: organiq puzzle where the pieces hum a forgotten melody
group: Applications/Games
vendor: maintainer
packager: Abdulwahab
packager_email: ab22593K@gmail.com
license: MIT
url: https://github.com/ab22593k/leafz

keywords:
  - Puzzle
  - Game

generic_name: Musical Puzzle Game

categories:
  - Game

startup_notify: true
