display_name: Leafz
package_name: leafz
maintainer:
  name: Abdulwahab
  email: ab22593K@gmail.com
priority: optional
section: games
installed_size: 102400
essential: false
icon: assets/app-icon-with-dash-ltr.png
postinstall_scripts:
  - echo "Leafz installed successfully"
postuninstall_scripts:
  - echo "Leafz uninstalled"
keywords:
  - Puzzle
  - Game
generic_name: Musical Puzzle Game
categories:
  - Game
startup_notify: true
